"""The declarative achievement catalogue. Each entry is one `_spec(...)`; the
mechanics that evaluate them live in `core` (the `Tally` a spec's check reads)
and `engine` (the detector that runs the checks). Adding an achievement is
usually a one-line entry here plus, if it needs a new stat, a `Tally` field."""

from services.achievements.core import (
    CHRONICLER_UPLOADS,
    UNDERDOG_UNITS,
    AchievementSpec,
    _career,
    _career_len,
    _live,
    _race_wins,
    _spec,
    is_secret,
)

SPECS: list[AchievementSpec] = [
    # Career tier ladders end WELL above the current record holder (2026-07:
    # 347 games, 216 wins, 41 units won with, 16.4k units built, 184
    # repicks, 54 teammates): at the most active pace (~175 games/yr) each
    # top rung is a multi-year chase, so there is always something to play
    # for. Epic rungs may be held; Legendary rungs must be years out.
    # -- career: volume ---------------------------------------------------
    _spec("first_game", "Fresh Meat", "🐣", "Common", "Play your first monobattle", _career("games", 1)),
    _spec("settling_in", "Settling In", "🏕️", "Common", "Play 10 games", _career("games", 10)),
    _spec("regular", "Regular", "🪑", "Common", "Play 25 games", _career("games", 25)),
    _spec("veteran", "Veteran", "🎖️", "Rare", "Play 100 games", _career("games", 100)),
    _spec("lifer", "Lifer", "🗿", "Epic", "Play 300 games", _career("games", 300)),
    _spec("millennium", "Millennium", "♾️", "Legendary", "Play 1,000 games", _career("games", 1000)),
    _spec("first_win", "On the Board", "✅", "Common", "Win your first game", _career("wins", 1)),
    _spec("warming_up", "Warming Up", "💪", "Uncommon", "Win 10 games", _career("wins", 10)),
    _spec("proven", "Proven", "📈", "Uncommon", "Win 25 games", _career("wins", 25)),
    _spec("centurion", "Centurion", "🏛️", "Epic", "Win 100 games", _career("wins", 100)),
    _spec("warlord", "Warlord", "👑", "Legendary", "Win 500 games", _career("wins", 500)),
    # -- career: MVP ------------------------------------------------------
    _spec("first_mvp", "Star of the Game", "⭐", "Uncommon", "Earn your first MVP", _career("mvps", 1)),
    _spec("serial_star", "Serial Star", "🌟", "Rare", "Earn 10 MVPs", _career("mvps", 10)),
    _spec("constellation", "Constellation", "💫", "Epic", "Earn 25 MVPs", _career("mvps", 25)),
    _spec("supernova", "Supernova", "🌠", "Legendary", "Earn 250 MVPs", _career("mvps", 250)),
    # -- career: variety --------------------------------------------------
    _spec("sampler", "Sampler", "🍬", "Common", "Play 3 different units", _career_len("units_played", 3)),
    _spec("field_tester", "Field Tester", "🧪", "Common", "Play 10 different units", _career_len("units_played", 10)),
    _spec("connoisseur", "Connoisseur", "🍷", "Rare", "Play 25 different units", _career_len("units_played", 25)),
    _spec(
        "one_of_everything",
        "One of Everything",
        "📦",
        "Epic",
        "Play all 42 units",
        _career_len("units_played", 42),
    ),
    _spec(
        "ten_ways_to_win",
        "Ten Ways to Win",
        "🔟",
        "Uncommon",
        "Win with 10 different units",
        _career_len("units_won", 10),
    ),
    _spec("winning_hand", "Winning Hand", "🃏", "Epic", "Win with 25 different units", _career_len("units_won", 25)),
    # 42 = every unit the map has ever dealt (stable across 716+ archive
    # games); the collection capstone. Best so far: 41.
    _spec("royal_flush", "Royal Flush", "♠️", "Legendary", "Win with all 42 units", _career_len("units_won", 42)),
    _spec("triple_threat", "Triple Threat", "🔱", "Uncommon", "Win with all three races", _career_len("races_won", 3)),
    _spec(
        "exterminator",
        "Exterminator",
        "☠️",
        "Rare",
        "Defeat all 42 units",
        (
            lambda h: len(h.career.units_beaten) >= 42,
            lambda h: (len(h.career.units_beaten), 42),
        ),
    ),
    _spec("zoo_keeper", "Zoo Keeper", "🦎", "Rare", "Win with 8 different Zerg units", _race_wins("Zerg", 8)),
    _spec("machinist", "Machinist", "🔩", "Rare", "Win with 8 different Terran units", _race_wins("Terran", 8)),
    _spec("artificer", "Artificer", "🔮", "Rare", "Win with 8 different Protoss units", _race_wins("Protoss", 8)),
    _spec(
        "bottom_of_barrel",
        "Bottom of the Barrel",
        "🛢️",
        "Epic",
        f"Win with {', '.join(UNDERDOG_UNITS[:-1])}, and {UNDERDOG_UNITS[-1]} — the three lowest-winrate units",
        (
            lambda h: set(UNDERDOG_UNITS) <= h.career.units_won,
            lambda h: (len(set(UNDERDOG_UNITS) & h.career.units_won), len(UNDERDOG_UNITS)),
        ),
    ),
    _spec("squadmates", "Squadmates", "🤝", "Common", "Play with 5 different teammates", _career_len("teammates", 5)),
    _spec(
        "social_butterfly",
        "Social Butterfly",
        "🦋",
        "Rare",
        "Play with 20 different teammates",
        _career_len("teammates", 20),
    ),
    _spec(
        "knows_everybody",
        "Knows Everybody",
        "🌐",
        "Epic",
        "Play with 75 different teammates",
        _career_len("teammates", 75),
    ),
    _spec("specialist", "Specialist", "🎯", "Rare", "Win 10 games with the same unit", _career("best_unit_wins", 10)),
    _spec(
        "grandmaster_of_one",
        "Grandmaster of One",
        "🥋",
        "Legendary",
        "Win 25 games with the same unit",
        _career("best_unit_wins", 25),
    ),
    _spec("production_line", "Production Line", "🏭", "Epic", "Build 10,000 units", _career("units_built", 10000)),
    _spec("war_machine", "War Machine", "⚙️", "Legendary", "Build 50,000 units", _career("units_built", 50000)),
    _spec("second_thoughts", "Second Thoughts", "🤔", "Common", "Use your first repick", _career("repicks", 1)),
    _spec("serial_repicker", "Serial Repicker", "🎰", "Rare", "Repick 25 times", _career("repicks", 25)),
    _spec("wheel_of_fortune", "Wheel of Fortune", "🎡", "Epic", "Repick 400 times", _career("repicks", 400)),
    # -- career: rivalries & community ------------------------------------
    _spec("nemesis", "Nemesis", "⚔️", "Uncommon", "Beat the same opponent 10 times", _career("best_opponent_wins", 10)),
    _spec(
        "bodyguard", "Bodyguard", "🛡️", "Rare", "Win 15 games with the same teammate", _career("best_teammate_wins", 15)
    ),
    _spec(
        "chronicler",
        "Chronicler",
        "📜",
        "Rare",
        f"Upload {CHRONICLER_UPLOADS} replays",
        (lambda h: False, None),  # granted from upload counts, never derived
    ),
    # -- career: calendar -------------------------------------------------
    _spec(
        "weekend_warrior",
        "Weekend Warrior",
        "🏖️",
        "Rare",
        "Play on 5 different weekends",
        _career_len("weekend_days", 5),
    ),
    _spec(
        "regular_customer",
        "Regular Customer",
        "☕",
        "Epic",
        "Play in 8 consecutive calendar weeks",
        _career("best_week_run", 8),
    ),
    _spec(
        "anniversary",
        "Anniversary",
        "🎂",
        "Rare",
        "Play on the anniversary of your first game",
        _career("anniversary_games", 1),
    ),
    _spec("insomniac", "Insomniac", "🌃", "Epic", "Play 50 late-night games", _career("night_games", 50)),
    # -- moment: streaks (live only) --------------------------------------
    _spec("heating_up", "Heating Up", "♨️", "Common", "Win 3 games in a row", _live("best_streak", 3)),
    _spec("on_fire", "On Fire", "🔥", "Rare", "Win 5 games in a row", _live("best_streak", 5)),
    _spec("unstoppable", "Unstoppable", "🌋", "Epic", "Win 8 games in a row", _live("best_streak", 8)),
    _spec("the_run", "The Run", "☄️", "Legendary", "Win 10 games in a row", _live("best_streak", 10)),
    _spec(
        "bounce_back",
        "Bounce Back",
        "🏀",
        "Uncommon",
        "Win right after losing 3 or more in a row",
        _live("bounce_backs", 1),
    ),
    # -- moment: single-game feats (live only) ----------------------------
    _spec("rampage", "Rampage", "😤", "Rare", "Destroy 25,000 enemy value in one game", _live("max_kills", 25000)),
    _spec(
        "extinction_event",
        "Extinction Event",
        "🦖",
        "Legendary",
        "Destroy 50,000 enemy value in one game",
        _live("max_kills", 50000),
    ),
    _spec(
        "economic_crash",
        "Economic Crash",
        "📉",
        "Epic",
        "Destroy 10,000 economy in one game",
        _live("max_econ_killed", 10000),
    ),
    _spec(
        "scorched_earth",
        "Scorched Earth",
        "💥",
        "Epic",
        "Destroy 8,000 tech in one game",
        _live("max_tech_killed", 8000),
    ),
    _spec(
        "highway_robbery",
        "Highway Robbery",
        "🦝",
        "Rare",
        "Trade at 5x efficiency (2,000+ value lost)",
        _live("best_trade", 5.0),
    ),
    _spec(
        "pyrrhic_victory",
        "Pyrrhic Victory",
        "🩸",
        "Epic",
        "Win while losing 30,000+ of your own value",
        _live("max_lost_in_win", 30000),
    ),
    _spec(
        "one_man_army",
        "One-Man Army",
        "🦾",
        "Legendary",
        "Outkill the entire enemy team by yourself",
        _live("outkilled_enemy_team", 1),
        secret=True,  # not a tier of anything — a genuine surprise
    ),
    _spec("moral_victory", "Moral Victory", "🥈", "Uncommon", "Be the MVP of a game you lost", _live("losing_mvps", 1)),
    _spec(
        "wasted_brilliance",
        "Wasted Brilliance",
        "🥀",
        "Epic",
        "Destroy 30,000 enemy value in a game you lose",
        _live("max_kills_in_loss", 30000),
    ),
    _spec(
        "cheerleader",
        "Cheerleader",
        "📣",
        "Rare",
        "Win a 10+ minute game with under 1,000 value killed and lost",
        _live("did_nothing_wins", 1),
    ),
    _spec(
        "every_mineral_counts",
        "Every Mineral Counts",
        "💎",
        "Rare",
        "Win a 10+ minute game with a median bank under 200",
        _live("thrifty_wins", 1),
    ),
    _spec(
        "seeing_double",
        "Seeing Double",
        "👯",
        "Uncommon",
        "Win with two of the same unit on your team",
        _live("twin_wins", 1),
    ),
    _spec(
        "send_in_clones",
        "Send in the Clones",
        "🧬",
        "Legendary",
        "Win with three of the same unit on your team",
        _live("triplet_wins", 1),
    ),
    _spec(
        "dynamic_duo",
        "Dynamic Duo",
        "🦸",
        "Epic",
        "Win 5 games in a row with the same teammate",
        _live("best_duo_streak", 5),
    ),
    _spec(
        "hat_trick",
        "Hat Trick",
        "🎩",
        "Rare",
        "Earn 3 MVPs in one sitting",
        _live("best_session_mvps", 3),
    ),
    _spec(
        "purity_of_essence",
        "Purity of Essence",
        "🧫",
        "Epic",
        "Win with an all-Zerg team",
        (lambda h: h.live.pure_race_wins.get("Zerg", 0) >= 1, None),
    ),
    _spec(
        "purity_of_form",
        "Purity of Form",
        "🔷",
        "Epic",
        "Win with an all-Protoss team",
        (lambda h: h.live.pure_race_wins.get("Protoss", 0) >= 1, None),
    ),
    _spec(
        "purity_of_man",
        "Purity of Man",
        "🚬",
        "Epic",
        "Win with an all-Terran team",
        (lambda h: h.live.pure_race_wins.get("Terran", 0) >= 1, None),
    ),
    _spec(
        "welcoming_committee",
        "Welcoming Committee",
        "👋",
        "Uncommon",
        "Play in someone's first monobattle",
        _live("welcomes", 1),
    ),
    _spec(
        "fresh_blood",
        "Fresh Blood",
        "🌱",
        "Rare",
        "Win a game with three or more first-timers in the lobby",
        _live("fresh_blood_wins", 1),
    ),
    _spec(
        "old_guard",
        "Old Guard Reunion",
        "🏰",
        "Rare",
        "Play a game where all eight players have 50+ games",
        _live("veteran_lobbies", 1),
    ),
    _spec(
        "marathon_session",
        "Marathon Session",
        "🏃",
        "Uncommon",
        "Play 6 games in one sitting",
        _live("best_session", 6),
    ),
    _spec(
        "opening_act",
        "Opening Act",
        "🎬",
        "Common",
        "Play in the game that kicks off a session night",
        _live("opening_acts", 1),
    ),
    _spec(
        "back_to_back",
        "Back-to-Back",
        "🔁",
        "Uncommon",
        "Be the MVP of two games in a row",
        _live("best_mvp_streak", 2),
    ),
    _spec(
        "the_prodigal",
        "The Prodigal",
        "🕊️",
        "Uncommon",
        "Win your first game back after 30+ days away",
        _live("return_wins", 1),
    ),
    _spec(
        "mirror_master",
        "Mirror Master",
        "🪞",
        "Uncommon",
        "Win a game where an opponent had your unit",
        _live("mirror_wins", 1),
    ),
    _spec(
        "never_doubted",
        "Never Doubted",
        "🔄",
        "Rare",
        "Win a comeback game (8,000+ behind)",
        _live("comeback_wins", 1),
    ),
    _spec(
        "along_for_the_ride",
        "Along for the Ride",
        "🎠",
        "Uncommon",
        "Win a 10+ minute game with the fewest kills in the lobby",
        _live("fewest_kills_wins", 1),
    ),
    _spec(
        "overqualified",
        "Overqualified",
        "🎓",
        "Rare",
        "Be the MVP while playing the lobby's worst unit by win rate",
        _live("underdog_mvps", 1),
    ),
    _spec("the_swarm", "The Swarm", "🐜", "Epic", "Build 500 units in one game", _live("max_units_one_game", 500)),
    _spec("no_regrets", "No Regrets", "🎲", "Common", "Win a game after repicking", _live("repick_wins", 1)),
    _spec(
        "blitz",
        "Blitz",
        "⚡",
        "Rare",
        "Win a game in under 5 minutes",
        (lambda h: h.live.fastest_win is not None and h.live.fastest_win < 300, None),
    ),
    _spec("the_closer", "The Closer", "🥊", "Uncommon", "Win a 20+ minute game", _live("max_win_duration", 1200)),
    _spec(
        "special_delivery",
        "Special Delivery",
        "🚁",
        "Rare",
        "Win a game with heavy drop or Nydus play",
        _live("delivery_wins", 1),
    ),
    _spec(
        "greed_is_good",
        "Greed Is Good",
        "🤑",
        "Rare",
        "Win after taking 3 bases before making a single unit",
        _live("greed_wins", 1),
    ),
    _spec(
        "orbital_farm",
        "Orbital Farm",
        "🛰️",
        "Rare",
        "Own 5 Orbital Commands in one game",
        _live("max_orbitals", 5),
    ),
    _spec(
        "great_wall",
        "Great Wall",
        "🧱",
        "Rare",
        "Build 50 static defense structures in one game",
        _live("max_static_defense", 50),
    ),
    _spec(
        "fortress_city",
        "Fortress City",
        "🏰",
        "Epic",
        "Build 100 static defense structures in one game",
        _live("max_static_defense", 100),
    ),
    _spec(
        "birdwatcher",
        "Birdwatcher",
        "🐦",
        "Rare",
        "Win a 10+ minute game with a unit that can't shoot up, against two or more air units",
        _live("grounded_wins", 1),
    ),
    _spec(
        "sticks_and_stones",
        "Sticks and Stones",
        "🪨",
        "Legendary",
        "Win a 10+ minute game where nobody on your team can shoot up, against an air unit",
        _live("team_grounded_wins", 1),
    ),
    _spec("long_haul", "The Long Haul", "🐢", "Epic", "Play a 30+ minute game", _live("longest_game", 1800)),
    _spec("night_shift", "Night Shift", "🦉", "Rare", "Play 10 late-night games", _live("night_games", 10)),
    # -- secret Easter eggs (live only; hidden until unlocked) -------------
    _spec(
        "deja_vu",
        "Déjà Vu",
        "🌀",
        "Rare",
        "Roll the same random unit 3 games in a row",
        _live("best_same_pick_run", 3),
        secret=True,
    ),
    _spec(
        "repick_regret",
        "The One That Got Away",
        "💔",
        "Uncommon",
        "Lose after repicking, while an opponent wins with the unit you gave up",
        _live("repick_regrets", 1),
        secret=True,
    ),
    _spec(
        "finders_keepers",
        "Finders Keepers",
        "🧲",
        "Uncommon",
        "Win with a unit an opponent repicked away from",
        _live("finders_keepers", 1),
        secret=True,
    ),
    _spec(
        "rubber_band",
        "Rubber Band",
        "🪀",
        "Uncommon",
        "Alternate wins and losses for 6 straight games",
        _live("best_alternation", 6),
        secret=True,
    ),
]

SPECS_BY_KEY = {s.key: s for s in SPECS}
SECRET_KEYS = {s.key for s in SPECS if is_secret(s)}
